# model
# dim-depth

seed: 2025

defaults:
  - _self_
  - model: dit-256-4

dataset:
  data_dir: "data/pretrain"
  meta_info_path: "data/pretrain/meta_info.json"
  sample_rate: 44100
  n_mel_channels: 128
  hop_length: 256
  max_frame_len: 512

training:
  learning_rate: 1e-3
  betas: (0.9, 0.95)
  weight_decay: 0.0
  batch_size_per_gpu: 64
  grad_accumulation_steps: 1
  max_grad_norm: 0
  max_steps: 100000
  warmup_ratio: 0.05
  save_per_steps: 10000
  test_per_steps: 2000
  wandb_project: "RIFT-SVC"
  wandb_run_name: "pretrain_${model.exp_name}_${training.max_steps}steps-lr${training.learning_rate}" 
  checkpoint_path: "ckpts/pretrain_${model.exp_name}_${training.max_steps}steps-lr${training.learning_rate}"
  num_workers: 16
  eval_sample_steps: 32
  eval_cfg_strength: 2.0
